version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dynamo
  api:
    image: reactive-starwars
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local
    environment:
      AWS_DYNAMODB_ENDPOINT: http://dynamodb-local:8000
    networks:
      - dynamo
networks:
  dynamo:
    driver: bridge
