name: test-and-build
on: [push]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        run: ./gradlew test
      - name: Build
        run: ./gradlew build
      - name: Package
        uses: actions/upload-artifact@v2
        with:
          name: reactive-starwars.jar
          path: build/libs/reactive-starwars*